import json


def booklinks():
    ebooks = {
        "SPEECH AND RESPECT": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Speech_and_Respect.pdf",
        "LIBERTY, LAW AND JUSTICE": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Liberty_law_and_Justice.pdf",
        "Human Rights, Serious Crime and Criminal Procedure": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Human_Rights_Serious_Crime_and_Criminal_Procedure.pdf",
        "Pragmatism and Theory in English Law": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Pragmatism_and_Theory_in_English_Law.pdf",
        "The Law": "http://c457332.r32.cf2.rackcdn.com/pdf/books/The_Law.pdf",
        "Considerations on India Affairs": "http:g//openarchive.in/docs/Books%20on%20Indian%20Legal%20History/Considerations%20on%20India%20affairs[189p,1772,William%20Bolts].pdf",
        "Mediation in Judicial Review: A practical handbook for lawyers": "http://www.nuffieldfoundation.org/sites/default/files/files/MJRhandbookFINAL.pdf",
        "The Development of Consumer Law and Policy - Bold Spirits and Timorous Souls": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Development_of_Consumer_law_and_Policy-Bold_Spirits_and_Timorous_Souls.pdf",
        "The Public Domain Enclosing the Commons of the Mind": "http://www.gutenberg.org/ebooks/27526",
        "A Search in Secret India": "http://sageevans.businesscatalyst.com/downloads/Paul-Brunton-A-Search-in-Secret-India.pdf",
        "Outline of US Legal System, 2004": "http://www.america.gov/media/pdf/books/legalotln.pdf#popup",
        "Media Law Handbook": "http://www.america.gov/media/pdf/books/media-law-handbook.pdf#popup",
        "Lincoln the unknown": "http://www.godfire.net/Lincoln_Unknown_Dale_Carnegie.pdf",
        "THE ENGLISH JUDGE": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_English_Judge2.pdf",
        "Indian Unrest": "http://www.gutenberg.org/cache/epub/16444/pg16444.html",
        "India Old and New": "http://www.gutenberg.org/files/15586/15586-h/15586-h.htm",
        "TURNING POINTS OF THE COMMON LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Turning_points_of_the_Common_Law.pdf",
        "The History and Constitution of the Courts and Legislative Authorities in India": "http://openarchive.in/docs/Books%20on%20Indian%20Legal%20History/The%20History%20And%20Constituion%20Of%20The%20Courts%20And%20Legislative%20Authorities%20In%20India%20Ed.%202nd[240p,1884,%20Cowell,%20Herbert,%20].pdf",
        "PUNISHMENT, PRISON AND THE PUBLIC": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Punishment_Prison_and_the_Public.pdf",
        "Law and Order": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Law_and_Order.pdf",
        "Labour and the Law": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Labour_and_the_Law.pdf",
        "FREEDOM UNDER THE LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Freedom_Under_the_Law_1.pdf",
        "TRIAL BY JURY": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Trial_by_Jury.pdf",
        "Mediation handbook 2013 2014": "http://old.clerksroom.com/downloads/422-The-Mediation-Handbook-2013-Printed.pdf",
        "Manual of Election Law, vol.1": "http://ceodelhi.gov.in/WriteReadData/ManualElectionLaw/MANUAL_OF_LAW_VOL_I.pdf",
        "Manual of Election Law, vol.2": "http://ceodelhi.gov.in/WriteReadData/ManualElectionLaw/MANUAL_OF_LAW_VOL_II.pdf",
        "EU Handbook on Mediation: Mediation Law and Practice in Other EU Countries": "http://mediation-net.eu/pdf/books/analysis_concise_text2.pdf",
        "JUDGE AND JURIST IN THE REIGN OF VICTORIA": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Judge_and_Jurist_in_the_Regin_of_Victoria.pdf",
        "Principles and practice of the law of Libel and Slander (1897)": "http://ia700300.us.archive.org/13/items/principlesandpra015170mbp/principlesandpra015170mbp.pdf",
        "Hindu Law (1st ed., 1905)": "http://ia600301.us.archive.org/9/items/hindulaw00ghar/hindulaw00ghar.pdf",
        "The Negative Side of Positive Law: Treatise": "http://ia600202.us.archive.org/20/items/TheNegativeSideOfPositiveLaw/3_positive_law_1.ps.pdf",
        "COMMERCIAL LAW IN THE NEXT MILLENNIUM": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Commercial_law_in_the_next_Millennium.pdf",
        "ENGLISH LAW AND THE MORAL LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/English_Law_and_the_Moral_law.pdf",
        "INDIA 2009: A Reference Annual": "http://www.publicationsdivision.nic.in/others/india_2009.pdf",
        "INDIA 2010: A Reference Annual": "http://www.publicationsdivision.nic.in/others/india_2010.pdf",
        "India 2011: A Reference Annual": "http://sumir.co.in/doc/India-Year-Book-2011.pdf",
        "Manual of Parliamentary Procedures in the Government of India": "http://mpa.nic.in/manual/Manual_English/Index.htm",
        "LAW AND LAWYERS IN THE UNITED STATES": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Law_and_Lawyers_in_the_United_States.pdf",
        "Criminal Psychology; a manual for judges, practitioners, and students": "http://www.gutenberg.org/ebooks/1320",
        "The British Legal System Today": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Hamlyn_Revisited_The_British_Legal_System_Today.pdf",
        "FROM THE TEST TUBE TO THE COFFIN Choice and Regulation in Private Life": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/From_the_Test_Tube_of_the_Coffin.pdf",
        "LAW OF ATTORNEY AND CLIENT (1896)": "http://ia600407.us.archive.org/33/items/lawofcontractssp00stpa/lawofcontractssp00stpa_bw.pdf",
        "EXECUTIVE DISCRETION AND JUDICIAL CONTROL": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Executive_Discretion_and_Judicial_Control.pdf",
        "THE LAND AND THE DEVELOPMENT or The Turmoil and the Torment": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Land_and_the_Development.pdf",
        "Law of Success in Sixteen Lessons": "http://ia600209.us.archive.org/18/items/Law_Of_Success_in_16_Lessons/law-of-success-napoleon-hill.pdf",
        "The Path of the Law": "http://www.gutenberg.org/ebooks/2373",
        "The Common Law": "http://www.gutenberg.org/ebooks/2449",
        "THE QUEST FOR SECURITY: EMPLOYEES, TENANTS, WIVES": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Quest_for_Security_Employees_Tenants_Wives_1.pdf",
        "THE QUEST FOR SECURITY: EMPLOYEES TENANTS, WIVES": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Quest_for_Security_Employees_Tenants_Wives_2.pdf",
        "The Fabric of English Civil Justice": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Fabric_of_English_Civil_Justice.pdf",
        "Access to Justice: Human Rights Abuses Involving Corporations India": "http://www.indianet.nl/pdf/AccessToJustice.pdf",
        "The New Constitution of India": "http://openarchive.in/docs/Books%20on%20Indian%20Legal%20History/The%20New%20Constitution%20Of%20India[220p,%201923,%20Sir%20Ilbert%20Courtenay].pdf",
        "The Government of India": "http://openarchive.in/docs/Books%20on%20Indian%20Legal%20History/The%20Government%20Of%20India[658p,1898,%20Ilbert,%20Courtenay,%20].pdf",
        "Upholding the Rule of Law and the Role of Judges and Lawyers in Times of Crisis: Legal Commentary to the ICJ Geneva Declaration": "http://documents.icj.org/Legal_Commentary_Geneva_Declaration.pdf",
        "Auto Biography of Jahangueir": "http://www.archive.org/stream/memoirsofemperor00jaharich#page/n59/mode/2up",
        "A Book About Lawyers": "http://www.gutenberg.org/ebooks/27785",
        "A Constitutional History of India": "http://openarchive.in/docs/Books%20on%20Indian%20Legal%20History/A%20Constitutional%20History%20Of%20India%201600%201935[560p,%201936,%20Keith%20Arthur%20Berriedale].pdf",
        "THE QUEEN'S PEACE": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Queens_Peace.pdf",
        "Legal Conundrums in our Brave New World": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Legal_Conundrums_in_our_Brave_new_World.pdf",
        "Treatise on the law of Fraud and Mistake, 3rd ed.": "http://ia600400.us.archive.org/16/items/cu31924022237774/cu31924022237774.pdf",
        "OTHER PEOPLE'S LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Other_People_Law.pdf",
        "Does the United Kingdom still have a constitution?": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Does_the_United_Kingdom_still_have_a_constitution.pdf",
        "Judicial Activism AUTHORITY, PRINCIPLE AND POLICY IN THE JUDICIAL METHOD": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Judicial_Activism.pdf",
        "THE BRITISH TRADITION IN CANADIAN LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_British_Tradition_in_Canadian_law.pdf",
        "Police Powers: Search and Seizure in criminal law enforcement_1983": "http://ia700808.us.archive.org/32/items/policepowerssear00lawr/policepowerssear00lawr.pdf",
        "THE RATIONAL STRENGTH OF ENGLISH LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Rational_Strength_of_English_Law.pdf",
        "Copyright Law of the United States of America: Contained in Title 17 of the United States Code": "http://www.gutenberg.org/ebooks/252",
        "A Guide to the Law of India": "http://openarchive.in/docs/Books%20on%20Indian%20Legal%20History/A%20Guide%20to%20the%20Law%20of%20India,%20Repealed%20and%20Unrepealed[145p,1872,Andrew%20Lyon].pdf",
        "PROTECTION FROM POWER UNDER ENGLISH LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Proctection_from_Power_Under_English_Law.pdf",
        "THE ADMINISTRATION OF JUSTICE": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Administration_of_Justice.pdf",
        "Ancient Law: Its Connection to the History of Early Society": "http://www.gutenberg.org/ebooks/22910",
        "India: What can it teach us": "http://www.gutenberg.org/files/20847/20847-h/20847-h.htm",
        "SOCIAL HISTORY AND LAW REFORM": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Social_History_and_law_Reform.pdf",
        "Principles of Common law Pleading (2nd revised edition,1917)": "http://famguardian.org/Publications/CommonLawPractice/Principles_of_Common_law_Pleading.pdf",
        "LAWYER AND LITIGANT IN ENGLAND": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Lawyer_and_Litigant_in_England.pdf",
        "THE NATIONAL INSURANCE COMMISSIONERS": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_National_Insurance_Commisioners.pdf",
        "Motor Accident Claims Referencer": "http://164.100.235.75/upload/asset/1445794112_MACR_Book.pdf",
        "INTOLERABLE INQUISITION? REFLECTIONS ON THE LAW OF TAX": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Intolerable_Inquisition_Reflections_on_the_Law_Tax_1.pdf",
        "THE INHERITANCE OF THE COMMON LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Inheritance_of_the_Common_law.pdf",
        "LAW OF BANKING (3rd edition, 1922)": "http://ia600502.us.archive.org/12/items/lawofbankingpage00pageiala/lawofbankingpage00pageiala_bw.pdf",
        "The United Kingdom and Human Rights": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_United_Kingdom_and_Human_Rights.pdf",
        "THE SANCTITY OF CONTRACTS": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Scanctity_of_Contracts_in_English_Law.pdf",
        "Common law pleading: its history and principles": "http://ia700302.us.archive.org/14/items/commonlawpleadi00stepgoog/commonlawpleadi00stepgoog.pdf",
        "Twelfth Five Year Plan 2012-17- Draft (Vol. 1)": "http://planningcommission.nic.in/plans/planrel/12thplan/pdf/vol_1.pdf",
        "Twelfth Five Year Plan 2012-17- Draft (Vol. 2)": "http://planningcommission.nic.in/plans/planrel/12thplan/pdf/vol_2.pdf",
        "Twelfth Five Year Plan 2012-17- Draft (Vol. 3)": "http://planningcommission.nic.in/plans/planrel/12thplan/pdf/vol_3.pdf",
        "First book of jurisprudence for students of the common law": "http://ia700404.us.archive.org/22/items/firstbookofjuris00polliala/firstbookofjuris00polliala_bw.pdf",
        "Background to Indian Law": "http://openarchive.in/docs/Books%20on%20Indian%20Legal%20History/Background%20to%20Indian%20Law[233p,1946,%20George%20Claus%20Rankin,%20].pdf",
        "Our Legal Heritage, 5th Ed.": "http://www.gutenberg.org/ebooks/13376",
        "THE CONTRIBUTION OF ENGLISH LAW TO SOUTH AFRICAN LAW; AND THE RULE OF LAW IN SOUTH AFRICA": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Contribution_of_English_Law_to_South_African_Law.pdf",
        "ENGLISH LAW THE NEW DIMENSION": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/English_Law_the_New_Dimension.pdf",
        "FREEDOM, LAW AND JUSTICE": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Freedom_Law_and_Justice.pdf",
        "THE COMMON LAW IN INDIA": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Common_Law_in_India.pdf",
        "The Principles of the Law of Crimes in British India": "http://openarchive.in/docs/Books%20on%20Indian%20Legal%20History/The%20principles%20of%20the%20law%20of%20crimes%20in%20British%20India[484p,1902,%20Syed%20Shamsul%20Huda].pdf",
        "Rambles and Recollections of an Indian Official": "http://www.gutenberg.org/files/15483/15483-h/15483-h.htm",
        "Introducing a European Legal Order": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Introducing_a_European_Legal_Order.pdf",
        "Managing a mediation process": "http://www.usip.org/sites/default/files/file/managing_mediation_process.pdf",
        "Justification and Excuse in the Criminal Law": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Justification_and_Excuse_in_the_Criminal_Law.pdf",
        "British Justice: The Scottish Contribution": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/British_Justice_The_Scottish_Contribution.pdf",
        "Digest of the law of evidence": "http://ia600500.us.archive.org/19/items/digestoflawofevi00stepuoft/digestoflawofevi00stepuoft_bw.pdf",
        "Hindu Law": "http://ia600304.us.archive.org/14/items/hindulaw014853mbp/hindulaw014853mbp.pdf",
        "JUSTICE IN THE WELFARE STATE": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Justice_in_the_Welfare_State_2.pdf",
        "THE EUROPEAN COMMUNITIES AND THE RULE OF LAW": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_European_Comminuties_and_the_Rule_of_Law.pdf",
        "My Reminiscences": "http://www.gutenberg.org/files/22217/22217-h/22217-h.htm",
        "NEW LAW FOR A NEW WORLD?": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/New_Law_for_a_New_World.pdf",
        "Hindu Law: as Administrated in British India (2nd Ed. , 1917)": "http://ia700508.us.archive.org/22/items/hindulaw025045mbp/hindulaw025045mbp.pdf",
        "BLACKSTONE'S TOWER: The English Law School": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Blackstone's_Tower.pdf",
        "Juvenile Justice in South Asia: Improving Protection for Children in Conflict with the Law": "http://www.unicef.org/rosa/Juvenile_Justice_in_South_Asia.pdf",
        "Manual for Administrative Law Judges (1993)": "http://ia700309.us.archive.org/32/items/gov.acus.1993.manual/manualforadmin1193unse.pdf",
        "CONSTITUTIONAL FUNDAMENTALS": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Constitutional_Fundamentals.pdf",
        "MALADMINISTRATION AND ITS REMEDIES": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Malaadministration_and_its_Remedies.pdf",
        "THE PROOF OF GUILT": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_Proof_of_Guilt.pdf",
        "Kerr on fraud and mistake": "http://ia600407.us.archive.org/13/items/cu31924022237782/cu31924022237782.pdf",
        "Protection of the Public - A New Challenge": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Proctection_of_the_Public_A_New_Challenge.pdf",
        "CRIME AND THE CRIMINAL LAW: REFLECTIONS OF A MAGISTRATE AND SOCIAL SCIENTIST": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/Crime_and_the_Criminal_Law_1.pdf",
        "THE STATE OF JUSTICE": "http://socialsciences.exeter.ac.uk/media/universityofexeter/schoolofhumanitiesandsocialsciences/law/pdfs/The_State_of_Justice.pdf"}

    return json.dumps({'ebooks': ebooks})
