def get_priv_pol():
    return '''
Dhuper Infotech Pvt. Ltd. , (“Dhuper Infotech”) operates several websites including dhuperinfotech.com, lawfacto.com and several mobile applications including the Law Facto android application. It is Dhuper Infotech’s policy to respect your privacy regarding any information we may collect while operating our websites and mobile applications.<br>
<br><h5>Website Visitors</h5><br>
Like most website and mobile application operators, Dhuper Infotech collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. In addition, the mobile application may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile devices unique device ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browsers you use, and information about the way you use the mobile application. Dhuper Infotech’s purpose in collecting non-personally identifying information is to better understand how Dhuper Infotech’s visitors use its websites and mobile applications. From time to time, Dhuper Infotech may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website. Dhuper Infotech also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users leaving comments on our blog. Dhuper Infotech only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below, except that blog commenter IP addresses and email addresses are visible and disclosed to the administrator of the blog.<br>
<br><h5>Gathering of Personally-Identifying Information</h5><br>
Certain visitors to Dhuper Infotech’s websites and mobile application choose to interact with Dhuper Infotech in ways that require Dhuper Infotech to gather personally-identifying information. The amount and type of information that Dhuper Infotech gathers depends on the nature of the interaction. For example, we ask visitors who sign up for account at Dhuper Infotech.com to provide their name, address contact number and email address. Those who engage in transactions with Dhuper Infotech – by purchasing access to Dhuper Infotech.com, for example – are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, Dhuper Infotech collects such information only insofar as is necessary or appropriate to fulfil the purpose of the visitor’s interaction with Dhuper Infotech. Dhuper Infotech does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website or mobile application related activities.<br>
<br><h5>Aggregated Statistics</h5><br>
Dhuper Infotech may collect statistics about the behaviour of visitors to its websites and mobile applications. For instance, Dhuper Infotech may monitor the most popular type of cases tracked and use it for general research. Dhuper Infotech may display this information publicly or provide it to others. However, Dhuper Infotech does not disclose personally-identifying information other than as described below.<br>
<br><h6>Protection of Certain Personally-Identifying Information</h6><br>
Dhuper Infotech discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Dhuper Infotech’s behalf or to provide services available at Dhuper Infotech’s websites and mobile applications, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using Dhuper Infotech’s websites, and/or Dhuper Infotech’s mobile application you consent to the transfer of such information to them. Dhuper Infotech will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Dhuper Infotech discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when Dhuper Infotech believes in good faith that disclosure is reasonably necessary to protect the property or rights of Dhuper Infotech, third parties or the public at large. If you are a registered user of a Dhuper Infotech website or mobile application and have supplied your email address, Dhuper Infotech may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with Dhuper Infotech and our products. We primarily use our blog to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. Dhuper Infotech takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.<br>
<br><h6>Cookies</h6><br>
A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. Dhuper Infotech uses cookies to help Dhuper Infotech identify and track visitors, their usage of Dhuper Infotech website, and their website access preferences. Dhuper Infotech visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using Dhuper Infotech’s websites, with the drawback that certain features of Dhuper Infotech’s websites may not function properly without the aid of cookies.<br>
<br><h6>Business Transfers</h6><br>
If Dhuper Infotech, or substantially all of its assets, were acquired, or in the unlikely event that Dhuper Infotech goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of Dhuper Infotech may continue to use your personal information as set forth in this policy.<br>
<br><h6>Privacy Questions</h6><br>
If you have any questions or concerns about Dhuper Infotech’s Privacy Policy or if you would like to make a complaint about a possible breach of local privacy laws, please contact us.<br>
<br><h6>Privacy Policy Changes</h6><br>
Although most changes are likely to be minor, Dhuper Infotech may change its Privacy Policy from time to time, and in Dhuper Infotech’s sole discretion. Dhuper Infotech encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site or the mobile application after any change in this Privacy Policy will constitute your acceptance of such change.
  '''
