def terms_conditions():
    return '''

    YOUR USE OF THIS mobile app CONSTITUTES YOUR AGREEMENT TO BE BOUND BY THESE TERMS AND CONDITIONS. <br><br>
This mobile app DHCBA (the "app") is a service made available by Dhuper Infotech  which shall be used solely under the following terms and conditions ("Terms of Use").<br><br>
1.	License. As a user of this application you are granted a nonexclusive, nontransferable, revocable, limited license to access and use the application and Content in accordance with these Terms of Use. Provider may terminate this license at any time for any reason. <br><br>

2.	Limitations on Use. The Content on this application is for personal use only and not for commercial exploitation. You may not decompile, reverse engineer, disassemble, rent, lease, loan, sell, sublicense, or create derivative works from the application or the Content. Nor may you use any network monitoring or discovery software to determine the site architecture, or extract information about usage or users. You may not use any robot, spider, other automatic device, or manual process to monitor or copy our application or the Content without Provider's prior written permission. You may not copy, modify, reproduce, republish, distribute, display, or transmit for commercial, non-profit or public purposes all or any portion of the application, except to the extent permitted above. You may not use or otherwise export or re-export the application or any portion thereof, the Content or any software available on or through the Web Site in violation of the export control laws and regulations of India. Any unauthorized use of the Web Site or its Content is prohibited. <br><br>

3.	Not Legal Advice. Content contained on or made available through the App is not intended to and does not constitute legal advice and no attorney-client relationship is formed, nor is anything submitted to this App treated as confidential. The accuracy, completeness, adequacy or currency of the Content is not warranted or guaranteed. Your use of information on the Web Site or materials linked from the App is at your own risk. <br><br>

4.	Intellectual Property Rights. Except as expressly provided in these Terms of Use, nothing contained herein shall be construed as conferring any license or right, by implication, estoppel or otherwise, under copyright or other intellectual property rights. You agree that the Content and Web Site is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws.
<br><br>
5.	No Solicitation. In no event may any person or entity solicit any Users with data retrieved from this App. <br><br>

6.	Advertisers. This Web Site may contain advertising and sponsorship. Advertisers and sponsors are responsible for ensuring that material submitted for inclusion on the App is accurate and complies with applicable laws. Provider will not be responsible for the illegality of or any error or inaccuracy in advertisers' or sponsors' materials. <br><br>

7.	Subscription. Certain sections of this App require you to register. If registration is requested, you agree to provide Provider with accurate, complete registration information. It is your responsibility to inform Provider of any changes to that information. Each registration is for a single person only, unless specifically designated otherwise on the registration page. Provider does not permit a) any other person using the registered sections under your name; or b) access through a single name being made available to multiple users on a network. You are responsible for preventing such unauthorized use. If you believe there has been unauthorized use, you must notify Provider immediately by emailing at support@lawfacto.com <br><br>

8.	 Errors and Corrections. Provider does not represent or warrant that the App will be error-free, free of viruses or other harmful components, or that defects will be corrected. Provider does not warrant or represent that the information available on or through the App will be correct, accurate, timely, or otherwise reliable. Provider may make improvements and/or changes to its features, functionality or Content at any time. <br><br>


9.	Third Party Content. Third party content may appear on this App or may be accessible via links from this App. Provider is not responsible for and assumes no liability for any mistakes, misstatements of law, defamation, slander, libel, omissions, falsehood, obscenity, pornography or profanity in the statements, opinions, representations or any other form of content contained in any third party content appearing on the App. You understand that the information and opinions in the third party content is neither endorsed by nor does it reflect the belief of Provider.

DISCLAIMER. The App Is Provided On An "As Is" Basis. Provider Expressly Disclaims All Warranties, Including The Warranties Of Merchantability, Fitness For A Particular Purpose And Non-Infringement. Provider Disclaims All Responsibility For Any Loss, Injury, Claim, Liability, Or Damage Of Any Kind Resulting From, Arising Out Of Or Any Way Related To (A) Any Errors In Or Omissions From This App And The Content, Including But Not Limited To Technical Inaccuracies And Typographical Errors, (B) Any Third Party Web Sites Or Content Therein Directly Or Indirectly Accessed Through Links In This Web Site, Including But Not Limited To Any Errors In Or Omissions Therefrom, (C) The Unavailability Of The App Or Any Portion Thereof, (D) Your Use Of This Web Site, Or (E) Your Use Of Any Equipment Or Software In Connection With The App.<br><br>

10.	Unlawful Activity. Provider reserves the right to investigate complaints or reported violations of the Terms of Use and to take any action we deem appropriate including but not limited to reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information. <br><br>
11.	Remedies for Violations. Provider reserves the right to seek all remedies available at law and in equity for violations of these Terms of Use, including but not limited to the right to block access from a particular Internet address to the Provider's Web sites and their features. <br><br>
12.	Governing Law and Jurisdiction. The Terms of Use are governed by and construed in accordance with the laws. All disputes relating to this End User License Agreement and its Terms and Conditions or claims arising therefrom will be subject exclusively to the jurisdiction of courts/forums/tribunals at New Delhi, India only. <br><br>
13.	Severability of Provisions. These Terms of Use incorporate by reference any notices contained on the App and the Privacy Policy constitute the entire agreement with respect to access to and use of the App. If any provision of these Terms of Use is unlawful, void or unenforceable then that provision shall be deemed severable from the remaining provisions and shall not affect their validity and enforceability. <br><br>
14.	Modifications
. This EULA may be modified any time by giving electronic notice to the subscriber. The subscribers continued use of the service shall be deemed to be an acceptance of the modified terms of the EULA.
 DHCBA reserves the right to modify its Subscription Policy from time to time. The Subscription Policy as well as the terms and conditions laid down therein shall be considered a part of this EULA. <br><br>

15. Intellectual Property
The subscriber agrees that the services contain trademarks, copyright, patents, designs and other intellectual property of DHCBA. The subscriber agrees that nothing in this agreement shall be construed to conferring any intellectual property right to the subscriber All rights not expressly granted herein are reserved. <br><br>

16.  Exclusion of Liability
i. The services offered by DHCBA require an internet connection to access its features. DHCBA is not responsible for any deficiency in services arising out of deficiency or on account of the internet connection of the subscriber. <br><br>
ii. While every reasonable effort will be made to ensure accuracy of information provided, DHCBA’s services are dependent on public data available on third-party websites. DHCBA does not guarantee the integrity, accuracy or quality of the information offered as a part of the service. Any discrepancies should be brought to DHCBA’s notice immediately. In any event, DHCBA will not be liable for any loss caused due to inaccurate information posted on its website. The user is cautioned to check the information with independent sources before relying on it. <br><br>
iii. DHCBA shall not be responsible for any delays, defaults or interruptions in the provision of service. <br><br>
iv. The services offered by DHCBA are provided to you “as is” with all faults, without warranty of any kind, without any assurances of performance or any other guarantees of any kind. The subscriber agrees to use the services at his own risk.
<br><br>
v.DHCBA does not make and hereby disclaims any and all implied or statutory warranties, including implied warranties of condition, uninterrupted use, compatibility, error-free service, accuracy of data, non-infringement of third-party rights and other warranties. <br><br>

17. Restriction on License
i.The subscriber agrees not to exploit the license commercially or use it for any purpose other than the permitted purposes.<br><br>
ii.The subscriber agrees not to distribute, lease, license, sell, rent, lend, convey, sub-license or otherwise transfer or assign the Services offered by DHCBA, any copies thereof, or any passwords or user-names of any DHCBA account, without the express prior written consent of DHCBA or as set forth in this EULA;<br><br>
iii.The subscriber agrees not to make a copy of the services offered by DHCBA or any part thereof, including but not limited to the data contained therein; <br><br>
iv.The subscriber agrees not to make the services offered by DHCBA publicly available or available on a network for use or download by multiple users;<br><br>
v. The subscriber agrees not to reverse engineer, decompile, disassemble, translate, prepare derivative works based on or otherwise modify the Services offered by DHCBA, in whole or in part; <br><br>
vi. The subscriber agrees not to, except as otherwise specifically provided by DHCBA or this EULA, use or install the Services offered by DHCBA (or permit others to do same) on a network, for on-line use, or on more than one computer at the same time;<br><br>
vii. The subscriber agrees not to remove, obscure or modify any copyright, trademark or other proprietary rights notices, marks or labels contained on or within the Services offered by DHCBA, falsify or delete any author attributions, legal notices or other labels of the origin or source of the material; <br><br>
viii. The subscriber agrees not to misrepresent the source of ownership of the DHCBA’s Services; <br><br>
ix. The subscriber agrees not to scrape, build databases or otherwise create permanent copies of content returned from the Services offered by DHCBA. <br><br>
x.The subscriber agrees not to copy extracts from the database used by DHCBA in offering its service or sell, reproduce or store it in any manner whatsoever. <br><br>
 xi. Advertisers. The App may contain advertisements. The inclusion of advertisements on the App does not imply endorsement of the advertised products or services. Dhuper Infotech shall not be responsible for any loss or damage of any kind incurred as a result of the presence of such advertisements on the App. Further, shall not be responsible or liable for the statements or conduct of any third party advertisers appearing on the App. You shall be solely responsible for any correspondence or transactions you have with any third party advertisers. <br><br>

18 Indemnification. To the fullest extent permitted by law, you shall defend, indemnify, and hold harmless the Dhuper Infotech Parties from and against all claims arising from or in any way related to your use of the App and/or App Content, a violation by you of these Terms of Use or Code of Conduct, or any other actions connected with your use of the Sites and/or App Content, including any liability or expense, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys fees. Dhuper Infotech will provide prompt written notice of any such claims, but failure to provide such notice will not release you from any of your obligations pursuant to this Section except to the extent that you are actually prejudiced by such failure, and will not relieve you from any other liability that you may have to the Dhuper Infotech Parties other than under this Section. <br><br>
19 User Generated Content. We welcome your views, comments and other communications, pictures, trackback URLs, or videos on our Sites which may include discussion boards, blogs and other services that allow users to provide feedback, comment or content ("User Content"). By contributing User Content to any of the Sites or social media profiles, users understand and acknowledge that this information is available to the public and grant the Dhuper Infotech a nonexclusive license to display, reproduce, transmit, modify such User Content and that the ABA may use the User Content for internal and external marketing purposes. You are solely responsible for the User Content you submit. If you believe any User Content infringes on your proprietary rights, contact the Dhuper Infotech’s Copyright Agent as identified in these Terms of Use. The ABA does not approve, endorse, or adopt any User Content, and the ABA assumes no liability for any User Content submitted by you or others. You agree to indemnify the ABA against all claims and liabilities resulting from User Content. Users who do not wish to have information they have made available via these sites used, published, copied and/or reprinted, should not post on the social media profiles. Please note that other participants may use posted information beyond the control of the Dhuper Infotech. All user content is read at your own risk, and the Dhuper Infotech recommends that you not rely on the information or advice in any of these postings. <br><br>
You acknowledge, consent and agree that the Duper Infotech may access, preserve and disclose your account information and the User Content you have posted by Users of the Services if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary in the sole opinion of the Dhuper Infotech to: (a) comply with legal process (b) respond to claims that any Content violates the rights of third parties; (c) respond to your requests for customer service; or d) protect the rights, property or personal safety of the Administrators, its Users and the public.
This Terms of Use is subject to amendment or modification at any time.
     '''
